name: Run Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:

  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: /app/
        run: npm i
      - name: Build
        working-directory: /app/
        run: npm run build
      - name: Run tests
        working-directory: /app/
        run: npm test --browsers ChromeHeadlessNoSandbox --watch=false