name: Run Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:

  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: DIRECTORY
        run: cd app/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: |
          npm run test --browsers ChromeHeadlessNoSandbox --watch=false